### ISSUE TITLE
Blender 3.x?

### ISSUE THREAD

**Issue by saberworks** [smlu/blender-sith#11]
I installed blender 3.0.1 on Linux Mint.  I can install the addon, and I get this message:

```
Modules Installed (sith) from '/home/brian/Desktop/JK Stuff/sith.zip' into '/home/brian/.config/blender/3.0/scripts/addons'
```

Once it's installed, I see a note next to it that says "Upgrade to 2.8x required."  But I already have 3.0.1.

When I try to enable it I get this message:

```
Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 387, in enable
    mod.register()
  File "/home/brian/.config/blender/3.0/scripts/addons/sith/__init__.py", line 675, in register
    bpy.types.INFO_MT_file_export.append(menu_func_export)
AttributeError: 'module' object has no attribute 'INFO_MT_file_export'
```

Any ideas?  Thank you!

**Comment by smlu** [comment]
Hey, sorry for late reply.. This plugin at current state only supports blender version 2.79b. The 2.80+ changed the addon API and is not backward compatible which is why you got this error.

**Comment by saberworks** [comment]
Thanks, I'll try the older version.
