### ISSUE TITLE
Doesn't install on Blender 2.79

### ISSUE THREAD

**Issue by ReindeerFloatilla** [smlu/blender-sith#9]
The addon doesn't install on 2.79. The page says for 2.79. Was this updated for a newer version? I tried a few later versions but none of them appear to be working. Please advise. 
https://cdn.discordapp.com/attachments/881034839401328683/1151470094384373852/image.png

**Comment by smlu** [comment]
What version of Python does Blender 2.79 use?
See also #3

**Comment by smlu** [comment]
Closing this since no additional info was provided.
